### ISSUE TITLE
README: For newbs... needs scikit-learn

### ISSUE THREAD

**Issue by EricForgy** [cstjean/ScikitLearn.jl#10]
I am just starting to learn machine learning in Julia and I have no experience with Python. ScikitLearn.jl looks like a nice place to start. I admit I had a hard time getting it to work. The installations instructions probably assume familiarity with Python (which I don't have).

To get ScikitLearn to work, I had to do a `Conda.add("scikit-learn")`. Probably obvious, but might be good to add to instructions for newbs like me.

Better yet, is there some way the build script can just add the python library to avoid that step?

**Comment by cstjean** [comment]
Hi Eric, installation is one of those things that's hard to test properly, so I appreciate the feedback. Could you describe what you did and the error messages? In theory you don't need the Python library `scikit-learn` installed if you're using the [Julia models](http://scikitlearnjl.readthedocs.io/en/latest/models/#julia-models). And if you want to use the Python models, `@sk_import linear_model: LogisticRegression` should have automatically installed `scikit-learn`. Did that not happen?

**Comment by cstjean** [comment]
Also, what Julia version are you on?

**Comment by EricForgy** [comment]
Hi @cstjean 

I was trying to follow this example:

https://github.com/cstjean/ScikitLearn.jl/blob/master/examples/Plot_Kmeans_Digits.ipynb

By copy/pasting to the REPL. The first 4 `using` statements were fine, but when I tried:

~~~julia
@pyimport sklearn.metrics as metrics
~~~

I got errors because it did not know what is `sklearn`.

After I tried `Conda.add("scikit-learn")`, I could run the whole example from the REPL and generate the charts (which was cool!).

~~~julia
julia> versioninfo()
Julia Version 0.5.0-rc3+0
Commit e6f843b (2016-08-22 23:43 UTC)
Platform Info:
  System: NT (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
~~~

**Comment by cstjean** [comment]
Ah, that's fair. ScikitLearn.jl used to require `scikit-learn`, and it was part of the installation instructions, but now that it's no longer necessary, I should update the examples accordingly. Sorry about the trouble. Let me know if you run into anything else. FYI I haven't tested 0.5 yet.
