### ISSUE TITLE
partial_fit! function not working  

### ISSUE THREAD

**Issue by athulsudheesh** [cstjean/ScikitLearn.jl#106]
While trying to use `partial_fit!` function I am getting the following error: 
```jl
ERROR: LoadError: KeyError: key :partial_fit not found
Stacktrace:
 [1] __getproperty(o::PyCall.PyObject, s::Symbol)
   @ PyCall ~/.julia/packages/PyCall/L0fLP/src/PyCall.jl:307
 [2] getproperty
   @ ~/.julia/packages/PyCall/L0fLP/src/PyCall.jl:312 [inlined]
 [3] partial_fit!(py_model::PyCall.PyObject, args::Matrix{Float64}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ ScikitLearn.Skcore ~/.julia/packages/ScikitLearn/ssekP/src/Skcore.jl:102
 [4] partial_fit!(py_model::PyCall.PyObject, args::Matrix{Float64})
   @ ScikitLearn.Skcore ~/.julia/packages/ScikitLearn/ssekP/src/Skcore.jl:102
```

**Comment by cstjean** [comment]
What model are you calling it on? Not all models support partial_fit.

**Comment by athulsudheesh** [comment]
I tried with two: pca and logistic regression. Got the same error for both.

**Comment by cstjean** [comment]
Looking around the docs, I'm not sure those support partial_fit. Eg. there is apparently [IncrementalPCA](https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.IncrementalPCA.html?highlight=partial_fit#sklearn.decomposition.IncrementalPCA.partial_fit) to explicitly support `partial_fit`. Maybe you can try with that?

**Comment by athulsudheesh** [comment]
Oh...Thank You @cstjean :)
It's working!!!!
