### ISSUE TITLE
warnings on 0.5

### ISSUE THREAD

**Issue by ViralBShah** [cstjean/ScikitLearn.jl#11]
Would be nice to fix these warnings that show up during precompilation as we prepare to release 0.5.

```
WARNING: deprecated syntax "[a=>b for (a,b) in c]".
Use "Dict(a=>b for (a,b) in c)" instead.

WARNING: deprecated syntax "call(self::PredictScorer, ...)".
Use "(self::PredictScorer)(...)" instead.

WARNING: deprecated syntax "call(::Core.kwftype(PredictScorer), ...)".
Use "(::Core.kwftype(PredictScorer))(...)" instead.

WARNING: deprecated syntax "[a=>b for (a,b) in c]".
Use "Dict(a=>b for (a,b) in c)" instead.

WARNING: deprecated syntax "[a=>b for (a,b) in c]".
Use "Dict(a=>b for (a,b) in c)" instead.
```

**Comment by cstjean** [comment]
Yes, I'll try to do so, thank you for the reminder. I haven't switched to 0.5 yet.

**Comment by ViralBShah** [comment]
That makes sense then. Thank you. Doing a machine learning talk and wanted to show off ScikitLearn.jl. Great notebooks! Will use 0.4.

**Comment by cstjean** [comment]
The 0.4 version has been stable for a while, and users haven't reported many issues, so is there a strong reason why I should bother with `Compat` and not just bump my `REQUIRE` to `Julia 0.5`?

**Comment by ViralBShah** [comment]
Compat can be a bit of a bother. However, there are a lot of 0.4 installations out there that will lose updates unless you really need to break compatibility. You may be best placed to judge (from your traffic stats) whether you should not worry about 0.4.

I do know that Madeleine Udell is planning to use it in her class at Cornell, and they are on 0.4, for example. 

@tkelman should probably chime in.

**Comment by tkelman** [comment]
If you don't mind maintaining a separate branch for 0.4 and backporting bug fixes, possibly also a feature or two to it, then it's feasible to maintain separate branches for 0.4 vs 0.5. But Compat is the more common approach.

**Comment by cstjean** [comment]
I'll take compat, it doesn't look like too much work, thank you for the feedback. I should have it ready by tonight.

> I do know that Madeleine Udell is planning to use it in her class at Cornell, and they are on 0.4, for example.

Awesome, I didn't know!

**Comment by cstjean** [comment]
Fixed on `master`. @ViralBShah Let me know if you run into other issues. Obviously I haven't thoroughly tested 0.5 yet, so it might be wiser to stick to 0.4 depending on what you want. It's unfortunate, but most of my testing was done through the example notebooks, and there's no automated way to rerun those at the moment.

**Comment by tkelman** [comment]
take a look at NBInclude.jl if most of your code is in notebook form and you haven't seen that

**Comment by ViralBShah** [comment]
Thanks!
