### ISSUE TITLE
Passing return_std to predict

### ISSUE THREAD

**Issue by evolbio** [cstjean/ScikitLearn.jl#117]
Various Scikitlearn models accept return_std=true when calling predict, for example BayesianRidgeRegressor, see [this example](https://scikit-learn.org/stable/auto_examples/linear_model/plot_bayesian_ridge_curvefit.html#plot-the-true-and-predicted-curves-with-log-marginal-likelihood-l). For example, with a BayesianRidgeRegressor or similar machine, I would like to call
```y_predict, y_std = predict(machine, X, return_std=true)```
I am using MLJ to make calls through ScikitLearn.jl. I have looked through ScikitLearn.jl and MLJScikitLearnInterface.jl and do not see anyway to make this work, but maybe I am missing something simple like the right way to pass additional arguments? Thanks.

**Comment by evolbio** [comment]
Very helpful response from @tlienart at [discourse](https://discourse.julialang.org/t/mlj-w-scikitlearn-passing-return-std-to-predict/91654/2?u=evolbio),  copied here:
--------------
You’re not missing something, there’s currently no way to pass that argument. It might be good to open an issue at MLJScikitLearnInterface to discuss this (and you could paste what follows).

I doubt that MLJ’s predict signature will be adapted to match this one but I’ll let [@ablaom](https://discourse.julialang.org/u/ablaom) or [@samuel_okon](https://discourse.julialang.org/u/samuel_okon) discuss that).

What could work is to pass the return_std as a new field of BayesianRidgeRegressor here [MLJScikitLearnInterface.jl/linear-regressors.jl at 36882f14321e7e9889aac31447eeed0102eb052f · JuliaAI/MLJScikitLearnInterface.jl · GitHub](https://github.com/JuliaAI/MLJScikitLearnInterface.jl/blob/36882f14321e7e9889aac31447eeed0102eb052f/src/models/linear-regressors.jl#L37)

then pick that up at predict time here [MLJScikitLearnInterface.jl/macros.jl at 36882f14321e7e9889aac31447eeed0102eb052f · JuliaAI/MLJScikitLearnInterface.jl · GitHub](https://github.com/JuliaAI/MLJScikitLearnInterface.jl/blob/36882f14321e7e9889aac31447eeed0102eb052f/src/macros.jl#L197)

this would also require ScikitLearn.jl to allow passing a return_std=true to predict, that might also require opening an issue there cc [@cstjean](https://discourse.julialang.org/u/cstjean)

**Comment by cstjean** [comment]
Hi @evolbio. We're generally aiming to match the scikit-learn python interface, so supporting `return_std=true` would be perfectly in line. It might be as simple as adding a `; kwargs...` somewhere. It would be a welcome contribution.

**Comment by tlienart** [comment]
I think this can be closed, this: https://github.com/cstjean/ScikitLearn.jl/blob/9f15da6c1daf49b30ed59c1dd0a5a30ec97ac7ab/src/Skcore.jl#L70-L104 

shows that kwargs can already be passed to `predict` and, indeed:

```
using ScikitLearn
@sk_import linear_model: BayesianRidge
X, y = randn(100,2), randn(100)
reg = BayesianRidge()
fit!(reg, X, y)
ym, ys = predict(reg, X, return_std=true)
```

just works, kudos to @cstjean for thinking generic from the start.
