### ISSUE TITLE
Problem with predict_proba

### ISSUE THREAD

**Issue by spiderpacman** [cstjean/ScikitLearn.jl#14]
Hello,

First, thanks for this very useful package!
I have a problem when trying to use the predict_proba function. I am running it on a linearSVC, ScikitLearn.predict_proba(svm_model,X) but I get the following error :

> ERROR: LoadError: KeyError: key "predict_proba" not found
 in getindex(::PyCall.PyObject, ::String) at /home/theo/.julia/v0.5/PyCall/src/PyCall.jl:261
 in #predict_proba#22(::Array{Any,1}, ::Function, ::PyCall.PyObject, ::Array{Float64,2}, ::Vararg{Array{Float64,2},N}) at /home/theo/.julia/v0.5/ScikitLearn/src/Skcore.jl:95

I am running on Linux, with every package updated

Thanks for your help

Theo

**Comment by cstjean** [comment]
LinearSVC does not support probabilistic predictions (the [methods section](http://scikit-learn.org/stable/modules/generated/sklearn.svm.LinearSVC.html) only has `predict`, not `predict_proba`). You'll need to pick a classifier with a probabilistic model, or maybe tack on calibration (not 100% sure that would work). I would recommend logistic/probit regression as a substitute for LinearSVC. Or DecisionTrees.jl for general modelling, with pure Julia.

**Comment by spiderpacman** [comment]
Oh thanks, I used SVC instead and it works perfectly fine :)
I just thought there would be a Platt Scaling with the linear SVC

**Comment by cstjean** [comment]
Sure!
