### ISSUE TITLE
DataFrameMapper and @sk_import preprocessing: StandardScaler 

### ISSUE THREAD

**Issue by Runespear** [cstjean/ScikitLearn.jl#16]
I am testing out the preprocessing example in the DataFrames section of the [manual](http://scikitlearnjl.readthedocs.io/en/latest/dataframes/)
I copied this code:
```julia
using ScikitLearn
using DataFrames: DataFrame, NA, DataArray
using DataArrays: @data
@sk_import preprocessing: (LabelBinarizer, StandardScaler)

data = DataFrame(pet=["cat", "dog", "dog", "fish", "cat", "dog", "cat", "fish"],
                 children=[4., 6, 3, 3, 2, 3, 5, 4],
                 salary=[90, 24, 44, 27, 32, 59, 36, 27])
mapper = DataFrameMapper([(:pet, LabelBinarizer()),
                          ([:children], StandardScaler())]);
round(fit_transform!(mapper, copy(data)), 2)
```
and tried to run it (I have all the packages installed already).

However, it seems that the ```StandardScaler()``` function interacts strangely for this part:
```julia
([:children], StandardScaler())]);
```
Since Julia v0.5 (and v0.4.5) throws this error:
```julia
LoadError: TypeError: #call#17: in new, expected Array{Tuple,1}, got Array{Tuple,1}
```

Strangely enough, it works as intended in Julia v0.6.0-dev without a hitch.

**Comment by cstjean** [comment]
Hi RuneSpear, thank you for filing out an issue about this, and sorry that I couldn't get back to you yesterday. That appears to be a bug in Julia. For whatever reason, the conversion to `Vector{Tuple}` fails. I've fixed it by explicitly typing the Array. If you `Pkg.checkout("ScikitLearn")`, it should be fixed.

Please report any other issue you encounter.

**Comment by cstjean** [comment]
[Issue in Julia](https://github.com/JuliaLang/julia/issues/19281)
