### ISSUE TITLE
Support for Saving Models

### ISSUE THREAD

**Issue by tawheeler** [cstjean/ScikitLearn.jl#18]
It would be very nice if we could save and load models.

I tried both of the [typical ways to do this](http://scikit-learn.org/stable/modules/model_persistence.html) with sklearn:

```
@pyimport pickle
open(model_save_path, "w") do io
        pickle.dump(model, io)
end
```

and 

```
@sk_import externals: joblib
joblib.dump(model, model_save_path)
```

Both give me an error caused by having jl-wrapped python objects.

ERROR: LoadError: PyError (:PyObject_Call) <type 'exceptions.TypeError'>
TypeError("can't pickle jlwrap objects",)

Is there a way around this?

**Comment by tawheeler** [comment]
Nevermind, I screwed up. It works just fine.
I was passing in a Julia type that contained a PyObject model field, rather than passing in the PyObject model directly.

**Comment by cstjean** [comment]
Saving models isn't completely solved, so I'll reopen the issue. Julia objects can in theory be saved with `JLD`, but there would be an issue saving a `Pipeline` object that contains Python models.

**Comment by ValdarT** [comment]
Any updates on this?

**Comment by cstjean** [comment]
Haven't worked on it. The correct solution would probably be to patch up either JLD.jl or PyCall.jl so that JLD would delegate to pickle for `PyObject`. Do you have a specific use case in mind? What object do you want to save?

**Comment by cstjean** [comment]
In practice, JLD.jl should work fine for storing pure-Julia pipelines. The only problem is for storing pipelines that contain Python models. You'd need to write some code similar to what @tawheeler wrote, but it wouldn't be difficult.

**Comment by ValdarT** [comment]
The use case would be to save a pipeline that contains Python models. Most preprocessing modules as well as models still need the original code so these come up quite often. There are of course ways around the issue but it would be nice to be able to "just save" them as in Python.

**Comment by cstjean** [comment]
Tentatively solved by [PyCallJLD](https://github.com/JuliaPy/PyCallJLD). I'm leaving this open until it's been registered and field-tested a bit. Use `Pkg.clone("https://github.com/JuliaPy/PyCallJLD.jl.git")` to try it out.

**Comment by msummerfield** [comment]
@cstjean - sorry, I think I broke it already!
The attached minimal example works on the smaller test data file (TestData-OK.csv), but fails on reload when used with the larger one (TestData.csv).

Julia Version 0.5.2-pre+1 (2017-03-06 03:59 UTC)
Commit a6c55c5 (60 days old release-0.5)
x86_64-linux-gnu

I hope this helps you track down the issue.

[BreakPyCallJLD.zip](https://github.com/cstjean/ScikitLearn.jl/files/978588/BreakPyCallJLD.zip)

**Comment by cstjean** [comment]
@msummerfield Thank you for the bug report. I tracked down the issue to a [string conversion problem](https://github.com/JuliaPy/PyCall.jl/issues/391). PyCallJLD can't handle letters with accents, and your CSV file contains "faã". Hopefully we can fix it soon, but in the meantime,  `CountVectorizer(ngram_range=(1, 1), max_df=0.75, binary=true, strip_accents="ascii")` solves the issue (in addition to being a pretty good data-cleaning step!  )

**Comment by msummerfield** [comment]
Thanks @cstjean, much appreciated!

**Comment by cstjean** [comment]
@msummerfield That was fixed, and [PyCallJLD](https://github.com/JuliaPy/PyCallJLD.jl) is now registered.
