### ISSUE TITLE
fit model gives error  "LoadError: UndefVarError: fit! not defined"

### ISSUE THREAD

**Issue by klezmen** [cstjean/ScikitLearn.jl#20]
Somehow it seems impossible to fit a model and keeps giving errors.
When i run this simple example:

using RDatasets: dataset
using ScikitLearn

@sk_import linear_model: LogisticRegression

iris = dataset("datasets", "iris")

X = convert(Array, iris[[:SepalLength, :SepalWidth, :PetalLength, :PetalWidth]])
y = convert(Array, iris[:Species])

model = fit!(LogisticRegression(), X, y)
accuracy = sum(predict(model, X) .== y) / length(y)
println("accuracy: $accuracy")  # accuracy on training set

LoadError: UndefVarError: fit! not defined

**Comment by cstjean** [comment]
Could you try it out in a fresh session? My guess is that you have imported a `fit!`function from another module (either DataFrames or StatsBase). If that's the case, you probably got an ambiguity warning at some point. You can fix it with `using ScikitLearn: fit!`. If you still have an issue, let me know what version of Julia and ScikitLearn you're on (use `Pkg.status()`)

**Comment by klezmen** [comment]
thanks!
this did the trick:

> 
using ScikitLearn: fit!

**Comment by eash11** [comment]
Hi
I tried the same code block and getting the following error. I also tried with using using ScikitLearn: fit!

Please advise

WARNING: redefinition of constant LogisticRegression. This may fail, cause incorrect answers, or produce other errors.
MethodError: no method matching getindex(::DataFrame, ::Vector{Symbol})
Closest candidates are:
  getindex(::DataFrame, ::AbstractVector{T}, ::Colon) where T at C:\Users\eashwar_n\.julia\packages\DataFrames\dgZn3\src\dataframe\dataframe.jl:599
  getindex(::DataFrame, ::AbstractVector{T}, ::Union{Colon, Regex, AbstractVector, All, Between, Cols, InvertedIndex}) where T at C:\Users\eashwar_n\.julia\packages\DataFrames\dgZn3\src\dataframe\dataframe.jl:573
  getindex(::DataFrame, ::AbstractVector, ::Union{AbstractString, Signed, Symbol, Unsigned}) at C:\Users\eashwar_n\.julia\packages\DataFrames\dgZn3\src\dataframe\dataframe.jl:524
  ...

Stacktrace:
 [1] top-level scope
   @ In[91]:8

**Comment by cstjean** [comment]
Two lines need to be changed because of the DataFrames changes...
```julia
X = convert(Array, iris[!, [:SepalLength, :SepalWidth, :PetalLength, :PetalWidth]])
y = convert(Array, iris[!, :Species])
```
