### ISSUE TITLE
Hyperparameter tuning with GridSearchCV does not work 

### ISSUE THREAD

**Issue by alexandergerber** [cstjean/ScikitLearn.jl#21]
Hi,
I am trying to reproduce an example from the package documentation (http://scikitlearnjl.readthedocs.io/en/latest/quickstart/#hyperparameter-tuning), but the code does not work.  The Julia version i am working with is: Version 0.6.0-dev.1258 (2016-11-16 17:32 UTC).

The line `fit!(LogisticRegression(), X, y)`  throws the following error:

> Cannot convert an object of type Array{Pair{Symbol,Float64}, 1} to an object of type Dict{Symbol,Any}. This may have arisen from a call to the constructor Dict{Symbol,Any}(...), since type constructors fall back to convert mode.

My code: 
```
using RDatasets: dataset
iris = dataset("datasets", "iris")
X = convert(Array, iris[[:SepalLength, :SepalWidth, :PetalLength, :PetalWidth]])
y = convert(Array, iris[:Species])

using ScikitLearn
using ScikitLearn.CrossValidation: cross_val_score
using ScikitLearn.GridSearch: GridSearchCV
@sk_import linear_model: LogisticRegression

gridsearch = GridSearchCV(LogisticRegression(), Dict(:C => 0.1:0.1:2.0))
fit!(LogisticRegression(), X, y)
println("Best parameters: $(gridsearch.best_params_)")
```

**Comment by cstjean** [comment]
Hi @alexandergerber, could you please try with the latest version (via `Pkg.checkout("ScikitLearn")`)? There was a recent fix for this, and I haven't tagged `ScikitLearn` with it yet.

**Comment by alexandergerber** [comment]
Thank you! With the newest version it is working.
