### ISSUE TITLE
Warn on old versions of sklearn-python

### ISSUE THREAD

**Issue by alexandergerber** [cstjean/ScikitLearn.jl#22]
Hi,
while `@sk_import linear_model: LogisticRegression` works fine I get an error when trying 
`@sk_import neural_network: MLPClassifier`. 

Is it possible with 'ScikitLearn.jl' to use neural networks?

**Comment by cstjean** [comment]
It works for me. What error are you getting? What version of `scikit-learn` do you have?
```julia
using PyCall
pyimport("sklearn")[:__version__]
```

I'd love to have support for one of the native Julia neuron network packages, but we'd have to speak with one of their maintainers first.

**Comment by alexandergerber** [comment]
Thanks for the fast reply. I apparently had an old version (0.17.1). With this I got the error 
> KeyError: key "MLPClassifier" not found. 

After updating to 0.18.1 the error vanished. 

I did set up Julia and Python just a couple of days ago. Hence I expected to have the newest package versions.

**Comment by cstjean** [comment]
No worries, glad to be of help. Maybe I should check the `scikit-learn` version when importing, because it seems like a frequent source of problem.
