### ISSUE TITLE
Creating Custom Transformer

### ISSUE THREAD

**Issue by mratsim** [cstjean/ScikitLearn.jl#23]
Hi team,

Thanks for the great package. I'm trying to build custom Transformer similar to the procedure described here : http://www.dreisbach.us/blog/building-scikit-learn-compatible-transformers/

```Python
# Python reference code
# Dumb transformer: it takes any data and returns a feature vector of [1].
from sklearn.base import TransformerMixin

class DumbFeaturizer(TransformerMixin):
    def __init__(self):
        pass

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        return [[1] for _ in X]
```

I'm working on the Kaggle titanic competition and try to pipeline every transformation from import to fit/predict.

Here is one of the function I'm trying to make into a Transformer.
It extracts the title from the "Name" column i.e from "Cumings, Mrs. John Bradley (Florence Briggs Thayer)" it will extract Mrs. and populate a new column from the extraction.

```Julia
function pp_Title(df::AbstractDataFrame)
    @linq df |>
        transform(
            CptTitle = map(s->match(r"(?<=, ).*?\.", s).match, :Name)
        )
end
```

Please note that I'm trying to builds transformers that accept Dataframes and output Dataframes as well. I will then use DataFrameMapper for the final transformation.

I tried using @pydef but it fails while fitting:

```Julia
@pydef type pp_extractTitle <: TransformerMixin
    fit(self, X, y=None) = return self
    
    transform(self, X)=
        @linq df |>
            transform(
                CptTitle = map(s->match(r"(?<=, ).*?\.", s).match, :Name)
            )
end
```

Thanks a lot

**Comment by cstjean** [comment]
Hi, it's nice to see ScikitLearn being stretched in new ways.

You can, and should, implement new transformers/models in straight Julia. See [ScikitLearnBase](https://github.com/cstjean/ScikitLearnBase.jl) for details. There's no equivalent to `TransformerMixin` at the moment. You can inherit from `BaseEstimator`, although it won't buy you much. I would start with 

```julia
using ScikitLearnBase

type DumbTransformer <: ScikitLearnBase.BaseEstimator
end

@declare_hyperparameters(DumbTransformer, [])

fit!(dt::DumbTransformer, X, y=nothing) = dt
function transform(dt::DumbTransformer, X::DataFrame)
   ... modify the columns and return a DataFrame
end
```

I haven't played with the Pipeline internals in a while so I can't guarantee that it will work, but please do ask again if you have any issue. This should be possible.

**Comment by mratsim** [comment]
Thanks @cstjean,

I managed to fit a model and use it for prediction with two custom transformers that accept and output Dataframe 👍 .
I had to battle a bit with the fit/transform and fit_transform imports  from DataFrames, DataFramesMeta, ScikitLearn and ScikitLearnBase but it's fine now.

```Julia
pipe = Pipelines.Pipeline([
    ("extract_title", PP_TitleTransformer()), #This is my function
    ("test",DumbTransformer()), #This is your example, transform function return the input X
     ("featurize", mapper), #This is a DataFrameMapper
    ("forest", RandomForestClassifier(ntrees=200))
    ])
```

Only issue after was Cross Validation with cross_val_score. It complained about simple_get_params due to the function signature Vector{Symbol}
```Julia
function simple_get_params(estimator, param_names::Vector{Symbol})
```

```Julia
Y_train = convert(Array, train[:Survived])
X_train = train


#Cross Validation - check model accuracy
round(cross_val_score(pipe, X_train, Y_train, cv =2), 2)
```
Output (I tried overloading once already):

```
LoadError: MethodError: no method matching simple_get_params(::PP_TitleTransformer, ::Array{Any,1})
Closest candidates are:
  simple_get_params(::PP_TitleTransformer, !Matched::Array{Symbol,1}) at In[13]:25
  simple_get_params(::Any, !Matched::Array{Symbol,1}) at /Users/<user>/.julia/v0.5/ScikitLearnBase/src/ScikitLearnBase.jl:47
while loading In[16], in expression starting on line 6
```

After changing param_names to accept "Any" type it worked fine.
```Julia
type DumbTransformer <: ScikitLearnBase.BaseEstimator
end

@declare_hyperparameters(DumbTransformer, [])

ScikitLearnBase.fit!(dt::DumbTransformer, X, y=nothing) = dt
function ScikitLearnBase.transform(dt::DumbTransformer, X::DataFrame)
   return X
end

import ScikitLearnBase.simple_get_params
function simple_get_params(estimator::DumbTransformer, param_names)
    # Not written as a comprehension for 0.3/0.5 compatibility
    di = Dict{Symbol, Any}()
    for name in param_names di[name] = getfield(estimator, name) end
    di
end
````

**Comment by cstjean** [comment]
>I had to battle a bit with the fit/transform and fit_transform imports from DataFrames

Yeah, the name clash is unfortunate. I use:

```julia
using ScikitLearn
using DataFrames
using ScikitLearn: fit!, transform     # disambiguation
```

Re. `Vector{Symbol}`: you're right, and I just changed the code to be more lenient. I would recommend using `@declare_hyperparameters(DumbTransformer, Symbol[])` on your side until the change gets tagged. It will work either way.
