### ISSUE TITLE
ScikitLearn.jl cannot find scikit-learn pkg

### ISSUE THREAD

**Issue by CorySimon** [cstjean/ScikitLearn.jl#27]
On Linux, Julia 0.5.1, I:

```
Pkg.add("ScikitLearn")
Conda.add("scikit-learn")
```

Then 

```
using ScikitLearn
@sk_import linear_model: LinearRegression
```

yields:

```
ERROR: PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('No module named sklearn.linear_model',)
```

Are there some environment variables I need to assert are set up correctly?

**Comment by CorySimon** [comment]
Oh, I solved it.

I `Pkg.rm()`'d Conda, ScikitLearn, and PyCall. Then, I `Pkg.add()`'d them back. Then I:
```
ENV["PYTHON"] = ""
Pkg.build("Conda")
Pkg.build("PyCall")
```

So I think oddly that PyCall was not looking in the right place by default.

**Comment by cstjean** [comment]
That's weird; I assumed that Conda would install its packages wherever PyCall is looking. Glad it worked out, in any case.

If anybody else has this problem, please leave a message here, this should be fixed.

**Comment by tibaes** [comment]
I got the same problem, and the solution above fixed the problem.
Running these after installing scikit-learn via conda.
`ENV["PYTHON"] = ""
Pkg.build("Conda")
Pkg.build("PyCall")`

**Comment by cstjean** [comment]
The latest tagged release (~2 hours ago) should have fixed this issue. If anyone encounters the problem, I'd appreciate posting an issue before using the above fix so that we can investigate.
