### ISSUE TITLE
Getting warning when importing some models and error when importing LogistivRegression

### ISSUE THREAD

**Issue by michaelkru** [cstjean/ScikitLearn.jl#28]
I'm trying to do the Quickstart example, but when running

`@sk_import linear_model: LogisticRegression`

I get the output:

```
WARNING: Method definition require(Symbol) in module Base at loading.jl:345 overwritten in module Main at /Users/user/.julia/v0.5/Requires/src/require.jl:12.
ERROR: LoadError: PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('No module named sklearn.linear_model',)

 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:265
 in _start() at ./client.jl:321
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/user/Dropbox/ML/beyes.jl, in expression starting on line 12
```

**Comment by cstjean** [comment]
What happens if you enter this at the REPL?
```julia
using PyCall
PyCall.pyimport_conda("sklearn", "scikit-learn")
```

**Comment by michaelkru** [comment]
When I ran that it installed sklearn, so I think the problem was that it was never installed. The program now runs correctly, except I still get:

`WARNING: Method definition require(Symbol) in module Base at loading.jl:345 overwritten in module Main at /Users/michaelkruger/.julia/v0.5/Requires/src/require.jl:12.`

**Comment by cstjean** [comment]
This warning is normal, and should be gone at the next ScikitLearn update. Thank you for filing an issue, it helped me find the problem. Let me know if you hit anything else.
