### ISSUE TITLE
Can I get attributes from the model?

### ISSUE THREAD

**Issue by xiaohk** [cstjean/ScikitLearn.jl#29]
If I use [Python `SVC` model](http://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html#sklearn.svm.SVC.fit), can I get attributes like `coef_`, `support_vectors_` from the fitted model?

**Comment by cstjean** [comment]
Yes; the model objects from Python are just regular [PyCall](https://github.com/JuliaPy/PyCall.jl) objects, so you can access their Python attributes with 

```julia
svc = fit!(SVC(), ...)
svc[:coef_]
svc[:support_vectors_]
```

**Comment by xiaohk** [comment]
@cstjean Oh I see! I tried to use `svc .coef_` and it didn't work lol.
