### ISSUE TITLE
fit! function

### ISSUE THREAD

**Issue by steffiel** [cstjean/ScikitLearn.jl#3]
Hi,

I want to use the DecisionTreeRegressor and the RandomForestRegressor, but when I tried the example the fit! function doesn't work. After installing all packages etc. 

Can you help me with this?

Thanks,
Steffie

**Comment by cstjean** [comment]
Sure, this is a very new implementation, bug reports are welcome. Could you post the code you tried and the error message/warnings? I just tried this:

```julia
using ScikitLearn
using DecisionTree: DecisionTreeClassifier, print_tree
using RDatasets: dataset

iris = dataset("datasets", "iris")
features = convert(Array, iris[:, 1:4]);
labels = convert(Array, iris[:, 5]);

# train full-tree classifier
model = DecisionTreeClassifier(pruning_purity_threshold=0.9)
fit!(model, features, labels)
# pretty print of the tree, to a depth of 5 nodes (optional)
print_tree(model.root, 5)
# apply learned model
predict(model, [5.9,3.0,5.1,1.9])
# get the probability of each label
predict_proba(model, [5.9,3.0,5.1,1.9])
println(get_classes(model)) # returns the ordering of the columns in predict_proba's output
# run n-fold cross validation over 3 CV folds
# See ScikitLearn.jl for installation instructions
using ScikitLearn.CrossValidation: cross_val_score
accuracy = cross_val_score(model, features, labels, cv=3)
```

and it worked.  Also make sure that you `Pkg.update()` before trying it out.

**Comment by steffiel** [comment]
Hi,

Thanks for the fast response! I attached a print screen of my errors after
I did the package update.
I need to rebuild the Python code in the attachment to Julia, in which
Xtrain is a N times 3 matrix, Ytrain a N times 12 matrix and Xtest a m
times 3 matrix in which m<N.

But I'm not sure if that is possible with these functions because I can not
try to fit them.

Thanks,
Steffie

2016-05-04 17:46 GMT-04:00 Cédric St-Jean <notifications@github.com>:

**Comment by cstjean** [comment]
Sorry, the screenshot didn't make it. I don't think you can make an attachment by email. If you reply on github, you can drag the screenshot into the text area. A link will appear, it works very well. Or you can just paste the code, enclosed in triple backticks: ```

Almost every file in the `examples` folder was translated from Python, there shouldn't be an issue.

**Comment by steffiel** [comment]
Oh my bad, does this work?:
![screen shot 2016-05-04 at 7 07 50 pm](https://cloud.githubusercontent.com/assets/19195334/15033187/31b660a0-1236-11e6-9dd1-f9fd46913b8b.png)
![screen shot 2016-05-04 at 7 08 01 pm](https://cloud.githubusercontent.com/assets/19195334/15033188/31b68b5c-1236-11e6-9efb-facdf8d1e333.png)
![screen shot 2016-05-04 at 7 12 21 pm](https://cloud.githubusercontent.com/assets/19195334/15033186/31b644ee-1236-11e6-8f69-be26f933d7af.png)

**Comment by cstjean** [comment]
Yes, it worked. The error is on the first line. Unfortunately, `ScikitLearn.jl` requires the Python version of `scikit-learn` to be installed, and you seem to be missing it. It's something that I'll be fixing in the next months - there's no reason for it to be a requirement. So you have two options:

- Replace `using ScikitLearn` with `using ScikitLearnBase`. You'll get `fit!`, `predict` etc., but you'll miss out on cross-validation, pipelines, ...
- Install scikit-learn. I wrote instructions on the [README](https://github.com/cstjean/ScikitLearn.jl#installation)

**Comment by steffiel** [comment]
Okay thanks, I will try this tomorrow!

**Comment by cstjean** [comment]
Hey, maybe you solved your issue some other way, but I took some time yesterday to strip out the Python dependency. Now installing scikit-learn.py and numpy is optional. If you want to try it out, `Pkg.checkout("ScikitLearn.jl")`.

**Comment by steffiel** [comment]
Hey, thank you. I still haven't solved the problem. I tried several things but I don't know how to translate the Python code to Julia since the fit! function can't take the N times 3 and N times 12 matrix to fit. Do you have any suggestions?

**Comment by cstjean** [comment]
If I'm understanding correctly, your input matrix has 3 features, and you have 12 different outputs per example? You're right, I don't think `DecisionTree.jl` supports that out-of-the-box. You could train 12 separate random forests, and it might work. It seems that [scikit-learn is smarter about it](http://scikit-learn.org/stable/modules/tree.html#multi-output-problems) than the naive approach, but if you have a big enough dataset, I don't think it would matter much.

The simplest solution is to install scikit-learn and `@sk_import ensemble: RandomForestRegressor`. There's an example [here](https://github.com/cstjean/ScikitLearn.jl/blob/master/examples/Decision_Tree_Regression.ipynb). 

Or you can file an issue/PR on DecisionTree.jl to implement the scikit-learn strategy in Julia.
