### ISSUE TITLE
Precompile error

### ISSUE THREAD

**Issue by jianghaizhu** [cstjean/ScikitLearn.jl#33]
I got the following error when `using ScikitLearn`.

```
julia> using ScikitLearn
INFO: Recompiling stale cache file /Users/zhuj6/.julia/lib/v0.6/ScikitLearn.ji for module ScikitLearn.
WARNING: The call to compilecache failed to create a usable precompiled cache file for module ScikitLearn. Got:
WARNING: Module Iterators uuid did not match cache file.
ERROR: LoadError: Declaring __precompile__(true) is only allowed in module files being imported.
Stacktrace:
 [1] __precompile__(::Bool) at ./loading.jl:335
 [2] __precompile__() at ./loading.jl:331
 [3] include_from_node1(::String) at ./loading.jl:569
 [4] eval(::Module, ::Any) at ./boot.jl:235
 [5] _require(::Symbol) at ./loading.jl:483
 [6] require(::Symbol) at ./loading.jl:398
while loading /Users/zhuj6/.julia/v0.6/ScikitLearn/src/ScikitLearn.jl, in expression starting on line 8
```

I am using Julia 0.6.0
```
julia> versioninfo()
Julia Version 0.6.0
Commit 903644385b (2017-06-19 13:05 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```

**Comment by cstjean** [comment]
That's https://github.com/cstjean/ScikitLearn.jl/issues/30. Restarting Julia should solve the problem, please let me know if it doesn't.

**Comment by jianghaizhu** [comment]
Well, restarting Julia once somehow was not working but restarting twice worked.

**Comment by cstjean** [comment]
Hmmm, that sucks. Hopefully Julia 6.1 works a bit better.

**Comment by fdgodabhi** [comment]
Encountered the same problem.
`julia> versioninfo()
Julia Version 0.6.2
Commit d386e40c17* (2017-12-13 18:08 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)`

using Juno-Atom and the error persists even after restarting Atom several times.

But there is no error if done using Julia by cmd.

**Comment by chasedehan** [comment]
I'm same as @fdgodabhi.  Can't get it to run in Juno, but runs fine from the terminal.

**Comment by chasedehan** [comment]
I was having the same problem as @fdgodabhi.  Worked from terminal, but not from Juno.  But, then after restarting it a few times, now it works.  Weird.

**Comment by ga73kud** [comment]
Julia Version 0.6.4

**Comment by cstjean** [comment]
At this point Julia 0.6/0.7 is not really supported anymore. But if you want to stick with it, I would recommend restarting Julia a few times.
