### ISSUE TITLE
Update to DataFrames v0.11

### ISSUE THREAD

**Issue by ValdarT** [cstjean/ScikitLearn.jl#36]
https://github.com/JuliaData/DataFrames.jl/issues/1232

**Comment by cstjean** [comment]
ScikitLearn has a test/REQUIRE dependency on RDatasets. Has that package been updated for 0.11? I think it's still pending.

**Comment by ValdarT** [comment]
Indeed. I didn't notice the extra requirements for tests.

**Comment by nalimilan** [comment]
RDatasets actually works with DataFrames 0.11.4, we've just fixed the dependencies on METADATA to reflect that. It will print deprecation warnings, but everything should work (waiting for a proper port).
