### ISSUE TITLE
Asking for scikit-learn (Python)

### ISSUE THREAD

**Issue by krzakala** [cstjean/ScikitLearn.jl#4]
I have the following message, but scikit-learn is definitly installed in python

WARNING: Please install scikit-learn (Python). See http://scikitlearnjl.readthedocs.io/en/latest/models/#installation for instructions.
ERROR: PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('No module named sklearn',)

**Comment by krzakala** [comment]
Got it! I was using conda.jl for python in julia. I installed ScikitLearn through conda and it works

**Comment by cstjean** [comment]
Sorry about that, the docs are written for `master`, which has the automated installation feature (pyimport-conda). Once PyCall tags another version, I'll tag one for ScikitLearn. @stevengj Did you intend to tag PyCall in the near future? Otherwise I might roll-back the `pyimport-conda` change and release ScikitLearn.jl

**Comment by krzakala** [comment]
Not sure what is the best option...

**Comment by stevengj** [comment]
There is a Travis failure in PyCall on Linux with Conda, I want to see if I can reproduce/fix it before I tag...

**Comment by stevengj** [comment]
@cstjean, it looks like the latest tagged version of PyCall (1.6.2) already has `pyimport_conda`).

**Comment by cstjean** [comment]
Oh, sorry, I misread the logs. 

FYI 1.6.2 was tagged, but I closed the PR to METADATA https://github.com/JuliaLang/METADATA.jl/pull/5219, so METADATA is still on 1.6.1

**Comment by stevengj** [comment]
Oh, that's confusing.  Maybe we should delete the 1.6.2 tag from the repo, then?

**Comment by stevengj** [comment]
The latest version of PyCall (https://github.com/stevengj/PyCall.jl/commit/4d7d476440e9094c2fad548b9165ce9bde01688a) is passing Travis; I think we can tag it assuming AppVeyor passes (modulo the random network hiccups that AppVeyor seems susceptible to).

**Comment by cstjean** [comment]
Yes, I agree.
