### ISSUE TITLE
DataFrames v0.11.6

### ISSUE THREAD

**Issue by KadeG** [cstjean/ScikitLearn.jl#42]
ScikitLearn is causing DataFrames to hang at version v0.10.1.

**Comment by cstjean** [comment]
The `master` supports DataFrames 0.11. Use `Pkg.checkout("ScikitLearn")` and it should fix the issue.

I can't tag this package yet (for reasons uninteresting), but hopefully soon.

**Comment by KadeG** [comment]
Alrighty. Thanks!

**Comment by cstjean** [comment]
I'll reopen until it's tagged in case someone else has the same problem.

**Comment by cstjean** [comment]
Tagged! Let me know if you have issues.
