### ISSUE TITLE
Current Arch python-sklearn invalid version string

### ISSUE THREAD

**Issue by aquaresima** [cstjean/ScikitLearn.jl#68]
Hi,
I am running `4.19.107-1-MANJARO`, 
current binaries of SKlearn are 
`python-scikit-learn 0.22.2.post1-1`

when I run
`
using ScikitLearn
@sk_import naive_bayes: GaussianNB
`

I get:
`
ERROR: ArgumentError: invalid version string: 0.22.2.post1
Stacktrace:
 [1] VersionNumber(::String) at ./version.jl:111
 [2] import_sklearn() at /home/cocconat/.julia/packages/ScikitLearn/bo2Pt/src/Skcore.jl:120
 [3] top-level scope at /home/cocconat/.julia/packages/ScikitLearn/bo2Pt/src/Skcore.jl:153
`

I solved hardcoding the version in \usr\lib....\sklearn\_init_.py and removig '.post1'. 
Please fix it

Best

**Comment by cstjean** [comment]
Thank you for the report. It's a dup of #67 , but if that's what's installed in some distros, we should indeed fix it. [This code](https://github.com/cstjean/ScikitLearn.jl/blob/78ff29e453afcf2578074a5f215d14575ae18a94/src/Skcore.jl#L120-L125) is just to send a warning, so we could wrap it in `try/catch` to ignore the error. Would you like to make a PR?
