### ISSUE TITLE
Using fit! with strings

### ISSUE THREAD

**Issue by degravek** [cstjean/ScikitLearn.jl#7]
I'm currently trying to use the "fit!" command to build a classification model. However, the features in my training set contain stings which seem to not be allowed by Python. I've found that one can use the Python functions "LabelEncoder" and "OneHotEncoder" to basically transform a set number of strings to numerical values. How can this be used through Julia? I've found that using @sk_import preprocessing: LabelEncoder actually works, but I'm not sure where to go from here. Thanks!

**Comment by cstjean** [comment]
Do you know about [pipelines](http://scikitlearnjl.readthedocs.io/en/latest/pipelines/)? If your input is in a dataframe, you can use something like

```julia
model = ScikitLearn.Pipelines.make_pipeline([DataframeMapper([([:string_column_name], LabelEncoder), ([:other_columns], nothing)]), LogisticRegression()])
```

If you can't figure it out, post the details of your input data. I've been using these functions for my own research, but they haven't been thoroughly tested yet...
