### ISSUE TITLE
Tests fail on MacOS

### ISSUE THREAD

**Issue by OkonSamuel** [cstjean/ScikitLearn.jl#75]
```
INTEL MKL ERROR: dlopen(/Users/travis/.julia/conda/3/lib/libmkl_intel_thread.dylib, 9): Library not loaded: @rpath/libiomp5.dylib

  Referenced from: /Users/travis/.julia/conda/3/lib/libmkl_intel_thread.dylib

  Reason: image not found.

Intel MKL FATAL ERROR: Cannot load libmkl_intel_thread.dylib.

ERROR: Package ScikitLearn errored during testing
```
Full log [here](https://travis-ci.org/github/cstjean/ScikitLearn.jl/jobs/691348147#L411)

This might be  an issue in Anaconda see [here](https://docs.anaconda.com/mkl-optimizations/)

**Comment by cstjean** [comment]
Thank you for the report. Do you have a mac? It would be good to know if the issue is travis-specific.

**Comment by OkonSamuel** [comment]
No i don't have a Mac. We experienced the same issue at MLJ and i thought it wise to check for it here.
From comments there it seems this issue is specific to **Conda** and using a different `PYTHON` backend for `PyCall` works.(so i think it should be travis specific)
