### ISSUE TITLE
Add DocumenterKey env variable to travis to enable doc deployment

### ISSUE THREAD

**Issue by OkonSamuel** [cstjean/ScikitLearn.jl#79]
@cstjean.`DOCUMENTER_KEY` env variable needs to be added to travis settings for this repo to enable doc deployment. 
See https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#travis-ssh-1 for how to do this.

I don't have sufficient permissions to do this.

**Comment by cstjean** [comment]
I did it, but it's my first time, so let me know if anything is wrong. I'll let you close.

**Comment by OkonSamuel** [comment]
works. https://cstjean.github.io/ScikitLearn.jl/dev/
It's dev until we tag a release

**Comment by cstjean** [comment]
Looks a lot better!

The link https://cstjean.github.io/ScikitLearn.jl/dev/man/examples_refer/ is broken.

**Comment by OkonSamuel** [comment]
fixed
