### ISSUE TITLE
Consider removing dependency over downstream packages

### ISSUE THREAD

**Issue by cstjean** [cstjean/ScikitLearn.jl#80]
My idea for ScikitLearn.jl  at the start was that each package would implement the `ScikitLearnBase.jl` interface, so that `ScikitLearn.jl` users wouldn't have everything installed. This is [not true anymore](https://github.com/cstjean/ScikitLearn.jl/blob/master/Project.toml) with the `DecisionTree` / `GaussianProcesses` / ... dependencies. 

@OkonSamuel Did you have a specific reason for putting them in the Project.toml? I'm not necessarily against it, but I think it should be discussed at least.

**Comment by OkonSamuel** [comment]
> @OkonSamuel Did you have a specific reason for putting them in the Project.toml? I'm not necessarily against it, but I think it should be discussed at least.

It's for those notebooks i think.
I'll look into it.

**Comment by cstjean** [comment]
Perhaps it would be sufficient to add a `# install with ]add GaussianProcesses` comment to those notebooks?
