### ISSUE TITLE
Links don't work and docs outdated

### ISSUE THREAD

**Issue by PallHaraldsson** [cstjean/ScikitLearn.jl#85]
"example gallery" link from the readme doesn't work:

https://github.com/cstjean/ScikitLearn.jl/blob/master/docs/examples.md

Seemingly the package works, and I got up to:

>accuracy: 0.9733333333333334

The docs say 0.96, for some reason, so I was going to update, but the "Edit" link in the right corner doesn't work:

https://github.com/cstjean/ScikitLearn.jl/edit/master/docs/quickstart.md

https://scikitlearnjl.readthedocs.io/en/latest/models/#installation
>Importing the Python models requires Python 2.7 with numpy, and the scikit-learn library. This is easiest to get through Conda.jl, which is already installed on your system.

I'm pretty sure I (only) Python3 scikitlearn installed (and only for 3.x still supported?)

I think I actually have Conda.jl, but while it's used by default on Windows I don't think it is on Linux.

Maybe change to Python 3.x or later (for some appropriate x, or just have x; and if Python 2.7 still works and you want it supported, "2.7 or 3.x" and later").

"JLD.jl is the preferred way of saving ScikitLearn.jl models."

I don't care too much either way, but should JLD2.jl also work and be mentioned?

**Comment by cstjean** [comment]
Thanks for all the feedback. I haven't had much time for this package in a while, but PRs are very appreciated. I'm not even entirely sure if Python 3 is supported, but if you can confirm that it is what's being used, and if it works well, then the docs should be updated for sure.

> I don't care too much either way, but should JLD2.jl also work and be mentioned?

JLD.jl has PyCallJLD, which uses pickle. I'm not sure about JLD2

**Comment by PallHaraldsson** [comment]
https://scikit-learn.org/stable/install.html#install-official-release
>Install the 64bit version of Python 3  [..] Scikit-learn now requires Python 3.6 or newer.

You're using Python 3 already (PyCall's default), unless you're changing:
https://github.com/cstjean/ScikitLearn.jl/commit/211d615b9714bd15293206da83e108d065dbef42

**Comment by OkonSamuel** [comment]
> https://scikitlearnjl.readthedocs.io/en/latest/models/#installation

@PallHaraldsson It appears your reading the old documentation.

**Comment by OkonSamuel** [comment]
> accuracy: 0.9733333333333334

The updated documentation actutally arrives at the above ans

**Comment by OkonSamuel** [comment]
@PallHaraldsson if your okay with the updated docs can we close this issue?

**Comment by PallHaraldsson** [comment]
https://scikitlearnjl.readthedocs.io/en/latest/models/#installation

still shows Python 2.7, but if I click "edit" in the corner there I get an error. I think maybe you updated the docs, but need to press some publish button?

**Comment by OkonSamuel** [comment]
@PallHaraldsson I meant you were using the old link. Here is the updated link https://cstjean.github.io/ScikitLearn.jl/dev/

**Comment by OkonSamuel** [comment]
@PallHaraldsson surely we can close this ?
