### ISSUE TITLE
Julia SciketLearn installation error

### ISSUE THREAD

**Issue by aathikm** [cstjean/ScikitLearn.jl#89]
Pkg.add("SciketLearn")

The following package names could not be resolved:
 * SciketLearn (not found in project, manifest or registry)

I'd face this issue on installation process..., Please help me any one

**Comment by OkonSamuel** [comment]
@aathikm should be `Pkg.add("ScikitLearn")` instead of `Pkg.add("SciketLearn")`

**Comment by aathikm** [comment]
@OkonSamuel Thank you. I'd fix this issue
