### ISSUE TITLE
ERROR: KeyError: AgglomerativeClustering not found

### ISSUE THREAD

**Issue by nw11** [cstjean/ScikitLearn.jl#9]
using ScikitLearn 
@sk_import cluster:AgglomerativeClustering
ERROR: KeyError: AgglomerativeClustering not found

I can import the other cluster functions without a problem
e.g.
@sk_import cluster: (estimate_bandwidth, MeanShift, MiniBatchKMeans, SpectralClustering)

Any ideas - would it be something to do with the local python scikitlearn installation?

**Comment by nw11** [comment]
I should have tested whether I could import using python, which I don't seem to be able to do.  This seems to be an issue with my local installation of scikitlearn.

**Comment by cstjean** [comment]
Yes, that should be it. Let me know if you encounter any other issue.
